name: gudang_elektrikal
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  google_fonts: ^6.2.1
  shimmer: ^3.0.0
  intl: ^0.19.0
  logger: ^2.3.0
  dropdown_search: ^5.0.6
  flutter_screenutil: ^5.9.3
  timeago: ^3.7.0
  flutter_image_compress: ^2.3.0
  image_cropper: ^8.0.1
  image_picker: ^1.1.2

dev_dependencies:
  flutter_lints: 4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
